version: '3'
services: 
    database:
        image: mongo
        ports:
            - 27017:27017
    server:
        restart: always
        build: backend
        links:
            - database
        depends_on: 
            - database
        ports: 
            - 9000:9000
        environment: 
            DB_HOST: database:27017
            TESTDB: CarManageTest
            DBNAME: CarManage
        env_file: 
            - 'backend/.env.production'
    frontend:
        restart: always
        stdin_open: true
        build: frontend
        ports: 
            - 3000:3000
        depends_on: 
            - server
        container_name: frontend